### ISSUE TITLE
Outdated example 

### ISSUE THREAD

**Issue by bes-internal** [perlancar/perl-Log-ger-Output-Composite#1]
https://github.com/perlancar/perl-Log-ger-Output-Composite/blob/7043e7013b2bdaa905196e7d0cae42782d7572a0/lib/Log/ger/Output/Composite.pm#L401-L410

Perhaps this example is outdated or simply incorrect or it just illustrative example. 
Anyway I used this and it doesn't work. Is it supposed to be like this?

```
Log::ger::Output->set(Composite => ( ### not ref but list
    # default_level => 'error', ### Unknown configuration: 'default_level' at /var/www/00host/core/2/vendor/local/lib/perl5/site_perl/5.36.1/Log/ger/Output/Composite.pm line 70.
    outputs => {
        File => { conf => {path=>'/foo', level=>'debug'}}, ### conf =>
        Screen => {level=>'info', category_level=>{MyApp=>'warn'}},
    },
    category_level => {
        'MyApp::SubModule1' => 'debug',
    },
));
```

**Comment by perlancar** [comment]
Hi, thanks for the issue. Fix is committed at e1d0b1c.
